name: 'weather_transform'
version: '1.0.0'
config-version: 2

profile: 'weather_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  weather_transform:
    +materialized: table
